# A functional, but probably terrible, example of GitLab CI for Flutter
image: cirrusci/flutter

variables:
before_script:
  - flutter channel dev
  - flutter upgrade

stages:
  - test
#  - build

lint:
  stage: test
  script:
    - flutter analyze

tests:
  stage: test
  script:
    - flutter test

#build:
#  stage: build
#  script:
#    - flutter build apk
