# A functional, but probably terrible, example of GitLab CI for Flutter
image: cirrusci/flutter

stages:
  - test
#  - build

lint:
  except:
    - schedules
  stage: test
  before_script:
    - flutter channel dev
    - flutter upgrade
  script:
    - flutter analyze

tests:
  except:
    - schedules
  stage: test
  before_script:
    - flutter channel dev
    - flutter upgrade
  script:
    - flutter test

mysql-activity:
  only:
    - schedules
  image:
    name: arey/mysql-client
    entrypoint: [""]
  script:
    - mysql --host=$DB_HOST --port=$DB_PORT --user=$DB_USER --password=$DB_PASS -e "UPDATE podcasts SET artworkOrig = artworkOrig ORDER BY id ASC LIMIT 1;" $DB_NAME

#build:
#  stage: build
#  script:
#    - flutter build apk
