# A functional, but probably terrible, example of GitLab CI for Flutter
image: cirrusci/flutter

variables:
before_script:
  - flutter channel dev
  - flutter upgrade

stages:
  - test
#  - build

lint:
  stage: test
  script:
    - flutter analyze

tests:
  stage: test
  script:
    - flutter test

mysql-activity:
  only:
    - schedules
  image:
    name: arey/mysql-client
    entrypoint: [""]
  script:
    - mysql -h $DB_HOST -P DB_PORT -D $DB_NAME -u $DB_USER -p $DB_PASS -D $DB_NAME -e $DB_ACTIVITY_STMT

#build:
#  stage: build
#  script:
#    - flutter build apk
