name: hear2learn
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+10

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter

  audioplayers: ^0.8.0
  cached_network_image: ^0.5.1
  dio: ^1.0.13
  dynamic_theme:
    path: ./packages/dynamic_theme
  flutter_cache_manager: ^0.2.0
  flutter_html: ^0.8.2
  flutter_redux: ^0.5.2
  http: '>=0.11.1 <0.12.0'
  intl: ^0.15.7
  jaguar_query_sqflite: ^2.2.5
  local_notifications: ^0.0.7
  package_info: ^0.4.0
  path: ^1.6.2
  path_provider: ^0.4.1
  percent_indicator: ^1.0.13
  redux: ^3.0.0
  redux_thunk: ^0.2.1
  shared_preferences: ^0.4.3
  sqflite: ^0.12.1
  swagger:
    path: ./packages/gpodder_client
  timeago: ^2.0.9
  transparent_image: ^0.1.0
  uuid: ^1.0.3
  webfeed: ^0.4.0

dev_dependencies:
  build_runner: ^1.1.2
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter
  jaguar_orm_gen: ^2.2.5
  test: any


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/01--default-fadein-image.jpg
   - images/02--default-fadein-image.jpg
   - images/03--default-fadein-image.jpg
   - images/04--default-fadein-image.jpg
   - images/05--default-fadein-image.jpg
   - images/06--default-fadein-image.jpg
   - images/07--default-fadein-image.jpg
   - images/08--default-fadein-image.jpg
   - images/drawer-header--balloons.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Italic.ttf
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-SemiBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
