swagger: '2.0'
info:
  description: Swagger for gpodder.net
  version: 1.0.0
  title: Swagger for gpodder.net
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: gpodder.net
basePath: /
schemes:
  - https
paths:
  /api/2/data/podcast.json:
    get:
      tags:
        - podcast
      summary: Get data about a podcast
      description: ''
      operationId: getPodcast
      produces:
        - application/json
      parameters:
        - in: query
          name: url
          description: Podcast url
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Podcast'
  /api/2/data/episode.json:
    get:
      tags:
        - episode
      summary: Get data about an episode
      description: ''
      operationId: getPodcastEpisode
      produces:
        - application/json
      parameters:
        - in: query
          name: url
          description: Episode url
          required: true
          type: string
        - in: query
          name: podcast
          description: Podcast url
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Episode'
  /api/2/tag/{tag}/{total}.json:
    get:
      tags:
        - podcast
      summary: Get data about a podcast
      description: ''
      operationId: getPodcastsByTag
      produces:
        - application/json
      parameters:
        - in: path
          name: tag
          description: Podcast tag
          required: true
          type: string
        - in: path
          name: total
          description: Number of podcasts to fetch
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Podcast'
  /search.json:
    get:
      tags:
        - podcast
      summary: Get list of top podcasts
      description: ''
      operationId: searchPodcasts
      produces:
        - application/json
      parameters:
        - in: query
          name: q
          description: Search query
          required: true
          type: string
        - in: query
          name: scale_logo
          description: Scaled logo percentage
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Podcast'
  /toplist/{total}.json:
    get:
      tags:
        - podcast
      summary: Search for podcasts
      description: ''
      operationId: getTopPodcasts
      produces:
        - application/json
      parameters:
        - in: path
          name: total
          description: Number of podcasts to fetch
          required: true
          type: integer
        - in: query
          name: scale_logo
          description: Scaled logo percentage
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Podcast'
definitions:
  Episode:
    properties:
      description:
        type: string
      mygpo_link:
        type: string
      title:
        type: string
      podcast_title:
        type: string
      podcast_url:
        type: string
      released:
        format: date-time
        type: string
      url:
        type: string
      website:
        type: string
  Podcast:
    properties:
      description:
        type: string
      logo_url:
        type: string
      mygpo_link:
        type: string
      scaled_logo_url:
        type: string
      subscribers:
        type: integer
      subscribers_last_week:
        type: integer
      title:
        type: string
      url:
        type: string
      website:
        type: string
